# Generated by Django 3.1.7 on 2021-03-31 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models.products


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Category type Description', max_length=100)),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Currency type Description', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol', max_length=100)),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('name', models.CharField(help_text='Customer name', max_length=240)),
                ('cellphone', models.CharField(help_text='Product name', max_length=20)),
                ('direction', models.TextField(help_text='Product name')),
                ('pay_method', models.CharField(help_text='Product name', max_length=120)),
                ('observations', models.TextField(help_text='Product name')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('name', models.CharField(help_text='Ingredient name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Ingredient description', null=True)),
                ('clasification', models.CharField(help_text='Ingrediente clasification', max_length=15)),
                ('quantity', models.IntegerField(blank=True, help_text='Ingredient quantity', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Place Description', max_length=100)),
                ('priority', models.IntegerField(blank=True, help_text='Level Priority', null=True, unique=True)),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('comments', models.TextField(help_text='Place Direction')),
                ('approved', models.DateTimeField()),
                ('done', models.DateTimeField()),
                ('cashier', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Cashier_a_Order', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Customer_a_Order', to='mainapp.customer')),
                ('level', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Level_a_Order', to='mainapp.level')),
                ('manager', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Manager_a_Order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Status type Description', max_length=100)),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Product price', max_digits=14)),
                ('change', models.DecimalField(decimal_places=4, help_text='Product price', max_digits=14)),
                ('cash_paid', models.DecimalField(decimal_places=4, help_text='Product price', max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=4, help_text='Product price', max_digits=14)),
                ('taxes', models.DecimalField(decimal_places=4, help_text='Product price', max_digits=14)),
                ('order', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Order_a_Receipt', to='mainapp.order')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipt_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipt_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipt_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Quantity type Description', max_length=100)),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantitytype_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantitytype_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantitytype_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('product_code', models.CharField(help_text='Product code', max_length=50)),
                ('name', models.CharField(help_text='Product name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Su imagen se re-dimensionara (200px~100px)', null=True, upload_to=mainapp.models.products.upload_to)),
                ('price', models.DecimalField(decimal_places=4, help_text='Product price', max_digits=14)),
                ('stock', models.IntegerField(blank=True, help_text='Product stock', null=True)),
                ('barcode', models.CharField(help_text='Product barcode', max_length=50)),
                ('category', models.ForeignKey(help_text='Fk to category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_Category_Product', to='mainapp.category')),
                ('currency', models.ForeignKey(help_text='Fk to currency', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_Currency_Product', to='mainapp.currency')),
                ('ingredients', models.ManyToManyField(blank=True, help_text='Fk ingredientes', related_name='relation_Ingredients_Product', to='mainapp.Ingredient')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Place Description', max_length=100)),
                ('direction', models.TextField(help_text='Place Direction')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=True, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('quantity', models.IntegerField(blank=True, help_text='OrderDetail quantity', null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Order_a_OrderDetail', to='mainapp.order')),
                ('product', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Product_a_OrderDetail', to='mainapp.product')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderdetail_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderdetail_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderdetail_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Place_a_Order', to='mainapp.place'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Status_a_Order', to='mainapp.status'),
        ),
        migrations.AddField(
            model_name='order',
            name='usuario_creo',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='usuario_elimino',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='usuario_modifico',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_type',
            field=models.ForeignKey(help_text='Fk a la dependencia correspondiente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_QuantityType_Ingredient', to='mainapp.quantitytype'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usuario_creo',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usuario_elimino',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usuario_modifico',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL),
        ),
    ]
