# Generated by Django 3.1.7 on 2023-07-06 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models.products


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Category type Description', max_length=100)),
                ('clave', models.CharField(help_text='Clave alfanumérica', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, help_text='Su imagen se re-dimensionara (200px~100px)', null=True, upload_to=mainapp.models.products.upload_to)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Currency type Description', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol', max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('name', models.CharField(help_text='Customer name', max_length=240)),
                ('cellphone', models.CharField(help_text='Customer cellphone', max_length=20, unique=True)),
                ('direction', models.TextField(blank=True, help_text='Customer direction', null=True)),
                ('pay_method', models.CharField(blank=True, help_text='Customer pay_method', max_length=120, null=True)),
                ('observations', models.TextField(blank=True, help_text='Customer observations', null=True)),
                ('email', models.EmailField(blank=True, help_text='Customer email field, to save the contact email', max_length=254, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('name', models.CharField(help_text='Ingredient name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Ingredient description', null=True)),
                ('clasification', models.CharField(help_text='Ingrediente clasification', max_length=15)),
                ('quantity', models.IntegerField(blank=True, help_text='Ingredient quantity', null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Place Description', max_length=100)),
                ('priority', models.IntegerField(blank=True, help_text='Level Priority', null=True, unique=True)),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('comments', models.TextField(help_text='Place Direction')),
                ('approved', models.DateTimeField(auto_now=True)),
                ('done', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14)),
                ('change', models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14)),
                ('cash_paid', models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14)),
                ('taxes', models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14)),
                ('pagado', models.BooleanField(default=False, help_text='Parametro que nos dira si la orden ya se ha pagado')),
                ('cocinado', models.BooleanField(default=False, help_text='Parametro que nos dira si la orden ya se ha cocinado')),
                ('entregado', models.BooleanField(default=False, help_text='Parametro que nos dira si la orden ya se ha entregado al cliente')),
                ('PaymentWithMercadoPago', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_PaymentWithMercadoPago_a_Order', to='adminapp.paymentwithmercadopago')),
                ('cashier', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que cobro la orden', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Cashier_a_Order', to=settings.AUTH_USER_MODEL)),
                ('cook', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que cocinara la orden', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Cook_a_Order', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer pagara la orden de existir', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Customer_a_Order', to='mainapp.customer')),
                ('dealer', models.ForeignKey(blank=True, default=None, help_text='Fk a usuario para conocer el usuario que entrego la orden', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Dealer_a_Order', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
                ('level', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Level_a_Order', to='mainapp.level')),
                ('manager', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Manager_a_Order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Status type Description', max_length=100)),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Quantity type Description', max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantitytype_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantitytype_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantitytype_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('product_code', models.CharField(help_text='Product code', max_length=50)),
                ('name', models.CharField(help_text='Product name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Su imagen se re-dimensionara (200px~100px)', null=True, upload_to=mainapp.models.products.upload_to)),
                ('price', models.DecimalField(decimal_places=4, help_text='Product price', max_digits=14)),
                ('stock', models.IntegerField(blank=True, help_text='Product stock', null=True)),
                ('barcode', models.CharField(help_text='Product barcode', max_length=50)),
                ('category', models.ForeignKey(help_text='Fk to category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_Category_Product', to='mainapp.category')),
                ('currency', models.ForeignKey(help_text='Fk to currency', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_Currency_Product', to='mainapp.currency')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
                ('ingredients', models.ManyToManyField(blank=True, help_text='Fk ingredientes', related_name='relation_Ingredients_Product', to='mainapp.Ingredient')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Place Description', max_length=100)),
                ('direction', models.TextField(help_text='Place Direction')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('description', models.CharField(help_text='Order Type Description', max_length=100)),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordertype_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordertype_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordertype_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no')),
                ('modificable', models.BooleanField(default=True, help_text='Parametro que nos dira si el registro puede ser modificado o no')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en el que el registro fue creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en el que el registro fue modifcado', null=True)),
                ('quantity', models.IntegerField(blank=True, help_text='OrderDetail quantity', null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.empresa')),
                ('order', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Order_a_OrderDetail', to='mainapp.order')),
                ('product', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Product_a_OrderDetail', to='mainapp.product')),
                ('usuario_creo', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderdetail_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL)),
                ('usuario_elimino', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderdetail_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderdetail_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(blank=True, default=None, help_text='Fk to Order Type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_OrderType_a_Order', to='mainapp.ordertype'),
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Place_a_Order', to='mainapp.place'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Status_a_Order', to='mainapp.status'),
        ),
        migrations.AddField(
            model_name='order',
            name='usuario_creo',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='usuario_elimino',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='usuario_modifico',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, default=None, help_text='Fk a usuario para conocer el usuario que tiene la orden como mesero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_Waiter_a_Order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_type',
            field=models.ForeignKey(help_text='Fk a la dependencia correspondiente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_QuantityType_Ingredient', to='mainapp.quantitytype'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usuario_creo',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que creo el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_con_relacion_a_usuariocreo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usuario_elimino',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que elimino el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_con_relacion_a_usuarioelimino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usuario_modifico',
            field=models.ForeignKey(blank=True, help_text='Fk a usuario para conocer el usuario que modifico el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_con_relacion_a_usuariomodifico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_code', 'empresa'), name='unique_product_code_empresa'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('clave', 'empresa'), name='unique_clave_empresa'),
        ),
    ]
