# Generated by Django 3.1.7 on 2021-03-31 23:49

from django.db import migrations, models
import mainapp.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Su imagen se re-dimensionara (200px~100px)', null=True, upload_to=mainapp.models.products.upload_to),
        ),
    ]
