# Generated by Django 3.1.7 on 2023-07-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='observaciones',
            field=models.TextField(blank=True, default=None, help_text='Observaciones del producto', null=True),
        ),
    ]
