# Generated by Django 3.1.7 on 2021-04-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_paid',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='change',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Product price', max_digits=14),
        ),
        migrations.AlterField(
            model_name='category',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='level',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='order',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='place',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='quantitytype',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.AlterField(
            model_name='status',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Parametro que nos dira si el objeto a sido eleminado o no'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
