# Generated by Django 3.1.7 on 2021-04-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210407_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
