version: '3.3'

services:
  web:
    restart: on-failure
    container_name: product_django_open_pos
    stdin_open: true
    tty: true
    environment:
      - DJANGO_DEBUG=FALSE
    build:
      context: ../../
      dockerfile: ""
    ports:
      - 8090:80
