FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    wget \
    libmariadbclient-dev \
    libssl-dev \
    python3.8 \
    python3.8-dev \
    python3-pip \
    supervisor \
    nginx

RUN pip3 install setuptools

RUN wget -O /wkhtmltox_0.12.1.4-2.bionic_amd64.deb \
    https://github.com/wkhtmltopdf/packaging/releases/download/0.12.1.4-2/wkhtmltox_0.12.1.4-2.bionic_amd64.deb

RUN apt-get -f install -y /wkhtmltox_0.12.1.4-2.bionic_amd64.deb

RUN ln -s /usr/local/bin/wkhtmltopdf /usr/bin &&\
    ln -s /usr/local/bin/wkhtmltoimage /usr/bin &&\
    rm -f /wkhtmltox_0.12.1.4-2.bionic_amd64.deb

RUN pip install uwsgi

RUN echo "daemon off;" >> /etc/nginx/nginx.conf

COPY docker/product_django_open_pos/nginx.conf /etc/nginx/sites-available/default

COPY docker/product_django_open_pos/supervisor.conf /etc/supervisor/conf.d/

RUN apt-get install -y python-m2crypto

RUN mkdir -p /var/www/django_open_pos

WORKDIR /var/www/django_open_pos

COPY docker/product_django_open_pos/uwsgi.ini /var/www/django_open_pos/uwsgi.ini

COPY requirements.txt /var/www/django_open_pos/requirements.txt

RUN pip3 install -r /var/www/django_open_pos/requirements.txt

COPY . /var/www/django_open_pos

RUN python /var/www/django_open_pos/manage.py collectstatic

EXPOSE 80

CMD ["supervisord", "-n"]
