from .index import Index
from .index import LoginView
from .index import LogoutView
from .index import categorias_view
from .index import dashboard
from .index import productos_view
from .index import carrito_view
from .index import eliminar_del_carrito
from .index import cobrar
